### ISSUE TITLE
调用绑定Tag方法出现错误

### ISSUE THREAD

**Issue by Zrincet** [OpenFlutter/rammus#11]
rammus: ^1.0.1
`List<String> bindList = ['lowBalance'];`

`var result = await rammus.bindTag(target: rammus.CloudPushServiceTarget.ACCOUNT_TARGET, tags: bindList);
`

E/MethodChannel#com.jarvanmo/rammus(26308): Failed to handle method call
E/MethodChannel#com.jarvanmo/rammus(26308): java.lang.ClassCastException: java.lang.Object[] cannot be cast to java.lang.String[]
E/MethodChannel#com.jarvanmo/rammus(26308): 	at com.jarvanmo.rammus.RammusPlugin.bindTag(RammusPlugin.kt:268)
E/MethodChannel#com.jarvanmo/rammus(26308): 	at com.jarvanmo.rammus.RammusPlugin.onMethodCall(RammusPlugin.kt:39)
E/MethodChannel#com.jarvanmo/rammus(26308): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:231)
E/MethodChannel#com.jarvanmo/rammus(26308): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:93)
E/MethodChannel#com.jarvanmo/rammus(26308): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:642)
E/MethodChannel#com.jarvanmo/rammus(26308): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#com.jarvanmo/rammus(26308): 	at android.os.MessageQueue.next(MessageQueue.java:336)
E/MethodChannel#com.jarvanmo/rammus(26308): 	at android.os.Looper.loop(Looper.java:182)
E/MethodChannel#com.jarvanmo/rammus(26308): 	at android.app.ActivityThread.main(ActivityThread.java:7550)
E/MethodChannel#com.jarvanmo/rammus(26308): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#com.jarvanmo/rammus(26308): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
E/MethodChannel#com.jarvanmo/rammus(26308): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:953)

**Comment by Zrincet** [comment]
不好意思，忘记说unbind方法也有这个问题了 @JarvanMo ，麻烦您了
